### ISSUE TITLE
Allow further arguments to be passed to run drupal:site-install or implement re-installing

### ISSUE THREAD

**Issue by bircher** [openeuropa/task-runner#68]
In Drupal 8.6 it is possible to re-install a site, or install a site from existing configuration.
See https://www.drupal.org/node/2897299

There is a drush PR for allowing drush to take advantage of this feature:
https://github.com/drush-ops/drush/pull/3625
currently this would allow a site to be installed with just `drush si -y --existing-config`.
Or `drush si -y --config-dir="path/to/config/sync"`

The current `drupal:site-install` would probably have to be updated, or a new command could be added. (requiring less arguments as the site name for example is already defined in config).

**Comment by ademarco** [comment]
Shall we create a new command called `drupal:site-config-install` that only works with `8.6.x`?

**Comment by dxvargas** [comment]
Option `existing-config` is already available.
https://github.com/openeuropa/task-runner/blob/1.0.0-beta6/src/Commands/AbstractDrupalCommands.php#L129
